name: snapshot-workflow
run-name: Build commit ${{ github.sha }} on branch ${{ github.ref }}
on: 
  push:
    branches:
      - develop
  pull_request:
jobs:
  build-snapshot:
    name: Build Snapshot
    runs-on: ubuntu-22.04
    steps:
      - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: '19'
          check-latest: true
          cache: 'maven'
      - name: Build & Test
        run: mvn --batch-mode -U clean verify
